### PR TITLE
updated PHP CS Fixer to new organization

### PR DESCRIPTION
**Pull request by mickaelandrieu**

### CODE REVIEW

**Comment by froschdesign** [comment]
For CS checks please use [zendframework/zend-coding-standard](https://github.com/zendframework/zend-coding-standard).

**Comment by froschdesign** [comment]
Look at this [pull request](https://github.com/zendframework/zend-mime/pull/21), which steps are needed to introduce the new module.

**Comment by mickaelandrieu** [comment]
this pull request shouldnt need any change, if it does this mean you are not compliant with PSR coding style..
closed :)

**Comment by demiankatz** [comment]
It would definitely be nice to get the outdated fabpot reference out of composer.json one way or another. Is somebody currently actively working on revising the coding standard setup for this repo? If not, I'm willing to volunteer to help with the work if it will expedite a 2.1.0 release -- but obviously I don't want to duplicate effort if somebody else already plans to do this.

**Pull request closed without merging**
