### PR TITLE
Update code style tools

### PR DESCRIPTION
**Pull request by demiankatz**
@Xerkus, here is a start on the code styles work; I've taken care of the low-hanging fruit of switching the tools and auto-fixing the styles that phpcbf can take care of. It looks like there's a fair amount of manual work still to be done. I will see how much of that I can get done tomorrow.

Is it acceptable to use annotations to ignore checks in cases like the `ZendService\Amazon\S3\Stream` class, where we are implementing a PHP interface that happens to be incompatible with Zend standards (non-camelcase method names)?

TODO
- [x] Get all style checks passing
- [x] Add docheader support

### CODE REVIEW

**Comment by demiankatz** [comment]
@Xerkus: one other question -- I assume I should go ahead and remove all the prefixed underscores from method names, but that is obviously going to cause BC breaks. Is there anything special I should be keeping in mind here, or will we just cover this with a major version bump and changelog note?

**Comment by Xerkus** [comment]
Yeah, underscored methods will need to be cs ignored.
As for the S3 stream, we can add targeted ignore for specific rule in phpcs.xml as it is a special case

**Comment by demiankatz** [comment]
@Xerkus, would it be helpful for me to convert the underscored methods into wrappers around non-underscored versions to make future deprecation easier? e.g.

<pre>
function myMethod()
{
    // move existing logic here....
}

/**
 * @deprecated
 */
function _myMethod()
{
    return $this->myMethod();
}
</pre>

Or is that overkill, and I should just leave things alone but flag them?

**Comment by Xerkus** [comment]
@demiankatz  I would prefer not to, at least for upcoming minor release. This component is from the times when extending classes weren't frowned upon and actually encouraged. 
I believe this component is due for major overhaul for v3 anyway

**Comment by demiankatz** [comment]
@Xerkus, thanks -- I'll leave the code alone but leave comments to remind us about future work. I did take the liberty of removing underscores from properties and method names in the test suite, as I think this is pretty safe. I've separated that work to its own commit (https://github.com/zendframework/ZendService_Amazon/pull/68/commits/33337fbf4db6817f462c6cfbaaa812ca8ec258e6) so it can be easily revised if you feel it was a mistake.

I still have quite a bit of work to get through to get everything passing, but I'll keep at it as time permits and let you know when I feel this PR is complete.

**Comment by Xerkus** [comment]
Switch to master and rebase please

**Comment by demiankatz** [comment]
@Xerkus, thanks for the release. I've rebased this and will continue finishing up the remaining style issues (and docheader support) as time permits.

**Comment by demiankatz** [comment]
@Xerkus, I believe that this is now complete. Please let me know if any changes are needed.

**Comment by Xerkus** [comment]
@demiankatz since you are moving test files, i suggest you to move them for psr-4 instead.
otherwise looks good

**Comment by Xerkus** [comment]
actually nevermind, whole thing could be updated to follow psr-4 in separate PR

**Comment by demiankatz** [comment]
Good idea. After this is merged, I can work on that next.

**Pull request merged**
