### PR TITLE
PHP 7.2 + QA Tools

### PR DESCRIPTION
**Pull request by webimpress**

### CODE REVIEW

**Comment by weierophinney** [comment]
@webimpress Other than a small set of the the ZendService components (Apple\Apns, Google\C2dm, Google\Gcm, ReCaptcha, and Twitter), these components are no longer maintained, as the services either no longer exist (AgileZen, DeveloperGarden, etc.) or have official client libraries).

Now that GitHub has tools to archive repos, we'll likely start doing that soon.

**Comment by webimpress** [comment]
@weierophinney  So this one (ZendService_Amazon) is no longer supported?

**Comment by weierophinney** [comment]
Correct. Amazon ships its own client libraries, which are always up-to-date.

**Comment by webimpress** [comment]
Ok, closing it now. Thx!

**Pull request closed without merging**
